version: '3.7'
services:
  khalo_db:
    image: postgres:12.6
    container_name: khalo_db
    env_file: ../private/database.env

    volumes:
      - khalo_volume:/var/lib/postgresql/data/  # Path is where the container stores sql data
    ports:
      - 5432:5432

    restart: always

volumes:
  khalo_volume:
    external: true
    name: khalo_volume
